# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/lims
spring.datasource.username=postgres
spring.datasource.password=

# JPA and Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Brevo SMTP Configuration
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=7c1d15001@smtp-brevo.com
spring.mail.password=N1WOLv5cRfa90pSI
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

logging.level.org.springframework.mail=DEBUG

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.html

# Session management for HTTPS
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.sameSite=Lax

# If the app runs behind a proxy (like Render), ensure the headers are forwarded correctly
server.forward-headers-strategy=FRAMEWORK

# Set session timeout (optional, e.g., 30 minutes)
server.servlet.session.timeout=30m
